# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeadHunterChatFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for HeadHunterChat

  pod 'WebimClientLibrary'
  pod 'Typist'
  pod 'SwiftLint' 
  pod 'SDWebImage', '~> 4.0'
  pod 'NYTPhotoViewer'

end
